services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DATABASE: postgres
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - 5555:5432

  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 5000:5000
    depends_on:
      - database
    command: >
      sh -c "
        npx prisma migrate deploy &&
        node dist/index.js
      "

volumes:
  database: